import os
from pathlib import Path
from datetime import datetime, timezone
from typing import Any

class ExperimentLedger:
    """
    Forensic Experiment Ledger Generator.
    Projects the canonical Run Record into a human-verifyable Markdown report.
    Enforces Strict Spec v1 compliance.
    """
    
    VERSION = "v1"

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir

    def _render_header(self, record: dict) -> str:
        status_emoji = "✅ SUCCESS" if record["execution"]["status"] == "success" else "❌ FAILED"
        if record["execution"]["status"] == "interrupted":
            status_emoji = "⚠️ INTERRUPTED"
            
        return f"""# {record["identity"]["run_id"]}

**Status:** {status_emoji}  
**Experiment:** {record["identity"]["exp_id"]}  
**Workload:** {record["intent"]["workload_type"]}  
**Requested by:** {record["intent"]["requested_by"]}  

**Created:** {record["intent"]["created_at"]}  
**Started:** {record["execution"]["started_at"]}  
**Completed:** {record["execution"]["completed_at"] or "N/A"}  
**Duration:** {record["outcome"]["duration_s"]}s  

**Instance:** {record["execution"]["instance_id"]}  
**Exit Code:** {record["outcome"]["exit_code"]}  
"""

    def _render_meta_table(self, title: str, data: dict, mapping: dict) -> str:
        lines = [f"## {title}", "", "| Field | Value |", "| :--- | :--- |"]
        for key, label in mapping.items():
            val = data.get(key, "N/A")
            lines.append(f"| {label} | {val} |")
        return "\n".join(lines)

    def _render_logs(self, record: dict) -> str:
        def format_log(log_meta, name):
            content = log_meta["content"] or f"--- No {name} available ---"
            truncated = f" (Truncated by {log_meta['truncated_by']})" if log_meta["truncated_by"] else ""
            return f"### {name} tail{truncated}\n```text\n{content}\n```"

        return f"""## Logs

{format_log(record["logs"]["stdout"], "stdout")}

{format_log(record["logs"]["stderr"], "stderr")}
"""

    def _render_governance(self, record: dict) -> str:
        errors = record["governance"]["validation_errors"]
        error_md = "\n".join([f"- {e}" for e in errors]) if errors else "None"
        
        return f"""## Governance

- **Conformance:** {record["governance"]["conformance"]}
- **Legacy:** {record["governance"]["is_legacy"]}
- **Validation Errors:** {error_md}
"""

    def generate_markdown(self, record: dict) -> str:
        """
        Generates the full Markdown content for a Run Record.
        """
        # 1. Enforce Strict-Only Rule
        if record["governance"]["conformance"] != "spec_v1":
            raise ValueError(f"Ledger generation requires strict Spec v1 compliance. Run {record['identity']['run_id']} is {record['governance']['conformance']}.")

        # 2. Render Sections
        sections = [
            self._render_header(record),
            "## Execution Summary\n\nThe run was processed by the TM4Server forensic governor.",
            self._render_meta_table("Intent (Run Manifest)", record["intent"], {
                "workload_type": "workload_type",
                "requested_by": "requested_by",
                "created_at": "created_at"
            }),
            self._render_meta_table("Execution Trace", record["execution"], {
                "status": "status",
                "instance_id": "instance_id",
                "worker_pid": "worker_pid",
                "started_at": "started_at",
                "updated_at": "updated_at",
                "phase": "phase",
                "progress": "progress",
                "attempt": "attempt"
            }),
            self._render_logs(record),
            self._render_governance(record),
            f"""---
Generated by: tm4server.ledger
Generator Version: {self.VERSION}
Generated At: {datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")}
Source: RunRecord (strict mode)
---"""
        ]
        
        return "\n\n".join(sections) + "\n"

    def write_ledger(self, record: dict) -> Path:
        """
        Writes the ledger document to disk atomically.
        """
        content = self.generate_markdown(record)
        run_id = record["identity"]["run_id"]
        out_path = self.output_dir / f"{run_id}.md"
        
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        tmp_path = out_path.with_suffix(".md.tmp")
        try:
            tmp_path.write_text(content, encoding="utf-8")
            os.replace(tmp_path, out_path)
            return out_path
        except Exception:
            if tmp_path.exists():
                tmp_path.unlink()
            raise
