import os
import json
import shutil
from pathlib import Path
from tm4server.execution.record import RunRecordBuilder, tail_log
from tm4server.execution.ledger import ExperimentLedger
from tm4server.execution.artifacts import write_manifest, write_status, write_summary, utc_now_z

def test_log_tailing():
    print("\n--- Testing Log Tailing (Dual-Constraint) ---")
    log_path = Path("test_tail.log")
    
    # Create 100 lines of text, totaling ~20KB
    lines = [f"Line {i:03d}: " + "X" * 200 + "\n" for i in range(100)]
    log_path.write_text("".join(lines), encoding="utf-8")
    
    # Test 50 lines / 16KB
    # Each line is 200 + 10 + 1 = 211 bytes.
    # 100 lines = 21,100 bytes.
    # 50 lines = 10,550 bytes.
    # 75 lines = 15,825 bytes.
    # 80 lines = 16,880 bytes. -> Should be truncated by bytes first.
    
    res = tail_log(log_path, max_lines=80, max_bytes=16384)
    print(f"Result (80 lines/16KB): Lines={res['lines']}, Bytes={res['bytes']}, Truncated={res['truncated_by']}")
    assert res["truncated_by"] == "bytes"
    
    # Test 10 lines
    res = tail_log(log_path, max_lines=10, max_bytes=16384)
    print(f"Result (10 lines/16KB): Lines={res['lines']}, Bytes={res['bytes']}, Truncated={res['truncated_by']}")
    assert res["truncated_by"] == "lines"
    
    log_path.unlink()

def test_split_brain():
    print("\n--- Testing Split-Brain Detection (Identity Consensus) ---")
    mock_root = Path("mock_intel_runs")
    if mock_root.exists(): shutil.rmtree(mock_root)
    mock_root.mkdir()
    
    run_dir = mock_root / "RUN-SPLIT"
    run_dir.mkdir()
    
    now = utc_now_z()
    
    # 1. Manifest for RUN-A
    write_manifest(run_dir, {
        "run_id": "RUN-A",
        "exp_id": "EXP-A",
        "workload_type": "test",
        "requested_by": "tester",
        "created_at": now
    })
    
    # 2. Status for RUN-B
    write_status(run_dir, {
        "run_id": "RUN-B", # MISMATCH
        "status": "running",
        "started_at": now,
        "worker_pid": 123
    })
    
    builder = RunRecordBuilder(mock_root)
    
    # Strict mode should reject
    record_strict = builder.build_record("RUN-SPLIT", strict=True)
    print(f"Strict Mode Record: {'REJECTED' if record_strict is None else 'ACCEPTED'}")
    assert record_strict is None
    
    # Compat mode should flag
    record_compat = builder.build_record("RUN-SPLIT", strict=False)
    print(f"Compat Mode Conformance: {record_compat['governance']['conformance']}")
    print(f"Validation Errors: {record_compat['governance']['validation_errors']}")
    assert "run_id mismatch: status (RUN-B) vs manifest (RUN-A)" in record_compat["governance"]["validation_errors"]
    
    shutil.rmtree(mock_root)

def test_ledger_generation():
    print("\n--- Testing Ledger Generation ---")
    mock_root = Path("mock_ledger_runs")
    if mock_root.exists(): shutil.rmtree(mock_root)
    mock_root.mkdir()
    
    run_id = "RUN-VALID-LEDGER"
    run_dir = mock_root / run_id
    run_dir.mkdir()
    
    now = utc_now_z()
    
    write_manifest(run_dir, {
        "run_id": run_id,
        "exp_id": "EXP-LEDGER",
        "workload_type": "ledger-test",
        "requested_by": "tester",
        "created_at": now
    })
    
    write_status(run_dir, {
        "run_id": run_id,
        "status": "success",
        "started_at": now,
        "worker_pid": 456
    })
    
    write_summary(run_dir, {
        "run_id": run_id,
        "exp_id": "EXP-LEDGER",
        "status": "success",
        "started_at": now,
        "completed_at": now,
        "exit_code": 0,
        "duration_s": 5,
        "artifact_root": str(run_dir)
    })
    
    builder = RunRecordBuilder(mock_root)
    record = builder.build_record(run_id, strict=True)
    
    ledger_dir = Path("mock_ledgers")
    if ledger_dir.exists(): shutil.rmtree(ledger_dir)
    ledger_dir.mkdir()
    
    ledger = ExperimentLedger(ledger_dir)
    out_path = ledger.write_ledger(record)
    print(f"Ledger written to: {out_path}")
    assert out_path.exists()
    
    content = out_path.read_text()
    print("Ledger Preview (first 10 lines):")
    print("\n".join(content.splitlines()[:10]))
    
    assert f"# {run_id}" in content
    assert "---" in content
    assert "Generated by: tm4server.ledger" in content
    
    shutil.rmtree(mock_root)
    shutil.rmtree(ledger_dir)

if __name__ == "__main__":
    try:
        test_log_tailing()
        test_split_brain()
        test_ledger_generation()
        print("\n[SUCCESS] Intelligence Layer Verification Complete.")
    except Exception as e:
        print(f"\n[FAILURE] Verification Failed: {e}")
        import traceback
        traceback.print_exc()
        exit(1)
